### ISSUE TITLE
[BUG] Dedicated server won't quit after stopping

### ISSUE THREAD

**Issue by yezhiyi9670** [tofodroid/mimi-mod#114]
**Describe the bug**

With version 1.20.1-4.0.0 or 1.20.1-4.0.1, the dedicated server won't stop entirely.

**To Reproduce**

1. Install 1.20.1 Forge server.
2. Install 4.0.0 or 4.0.1 version of the mod.
3. Agree EULA and start the server.
4. Type `stop` to stop server.
   ❎ Note that after saving world, the server process won't quit. You have to Ctrl-C it to quit completely.

**Expected behavior**

The server process should quit after saving world.

**Crash Logs**

The server just got stuck, without producing error info about this mod.

**Environment (please complete the following information):**

 - OS: Windows
 - Mod Version: 4.0.1
 - Minecraft Version: 1.20.1
 - Forge Version: 1.20.1-47.2.21

**Comment by tofodroid** [comment]
Hello and thank you for the bug report! I have not seen this issue before but will do some investigating to see if I can figure out what's causing the issue.

**Comment by tofodroid** [comment]
I believe I have found the cause of this issue and have just uploaded version 4.0.2 to CurseForge and Modrinth to fix it. Let me know if you still have issues with the new version!

**Comment by zeven1707** [comment]
Having the same issue. Server won't stop and log spits this out. No one has been on the server while it was running.
MC Version: 1.20.1
MIMI Version 4.0.5

`[03Apr2024 19:09:04.613] [Server thread/INFO] [io.github.tofodroid.mods.mimi.common.MIMIMod/]: MIMI - SERVER STOPPING
[03Apr2024 19:09:04.614] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "java.util.concurrent.ExecutorService.shutdown()" because "io.github.tofodroid.mods.mimi.server.midi.transmitter.ServerMusicTransmitterManager.pool" is null
	Index: 3
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/server/ServerStoppingEvent;)V
		2: NORMAL
		3: ASM: class io.github.tofodroid.mods.mimi.forge.common.CommonForgeEventHandler onServerStopping(Lnet/minecraftforge/event/server/ServerStoppingEvent;)V
		4: net.minecraftforge.eventbus.EventBus$$Lambda$1509/0x00000008013012a8@475b15cc
		5: net.minecraftforge.eventbus.EventBus$$Lambda$1509/0x00000008013012a8@67873a4d
		6: net.minecraftforge.eventbus.EventBus$$Lambda$1509/0x00000008013012a8@f1bbe72
		7: ASM: class com.ldtteam.structurize.event.EventSubscriber onServerStopped(Lnet/minecraftforge/event/server/ServerStoppingEvent;)V
		8: ASM: com.mrcrayfish.framework.event.ForgeEvents@2456f771 onServerStopping(Lnet/minecraftforge/event/server/ServerStoppingEvent;)V
		9: ASM: class com.simibubi.create.foundation.events.CommonEvents serverStopping(Lnet/minecraftforge/event/server/ServerStoppingEvent;)V
		10: net.minecraftforge.eventbus.EventBus$$Lambda$1509/0x00000008013012a8@3f72895f
		11: ASM: de.maxhenkel.voicechat.intercompatibility.ForgeCommonCompatibilityManager@4355c889 serverStopping(Lnet/minecraftforge/event/server/ServerStoppingEvent;)V
		12: ASM: pregenerator.common.manager.ServerManager@3fc674cc onServerStopped(Lnet/minecraftforge/event/server/ServerStoppingEvent;)V
		13: ASM: me.lucko.spark.forge.plugin.ForgeServerSparkPlugin@4762cf04 onDisable(Lnet/minecraftforge/event/server/ServerStoppingEvent;)V
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ExecutorService.shutdown()" because "io.github.tofodroid.mods.mimi.server.midi.transmitter.ServerMusicTransmitterManager.pool" is null
	at TRANSFORMER/mimi@1.20.1-4.0.5/io.github.tofodroid.mods.mimi.server.midi.transmitter.ServerMusicTransmitterManager.onServerStopping(ServerMusicTransmitterManager.java:95)
	at TRANSFORMER/mimi@1.20.1-4.0.5/io.github.tofodroid.mods.mimi.forge.common.CommonForgeEventHandler.onServerStopping(CommonForgeEventHandler.java:115)
	at TRANSFORMER/mimi@1.20.1-4.0.5/io.github.tofodroid.mods.mimi.forge.common.__CommonForgeEventHandler_onServerStopping_ServerStoppingEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.21/net.minecraftforge.server.ServerLifecycleHooks.handleServerStopping(ServerLifecycleHooks.java:122)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:671)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)

[03Apr2024 19:09:04.615] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ExecutorService.shutdown()" because "io.github.tofodroid.mods.mimi.server.midi.transmitter.ServerMusicTransmitterManager.pool" is null
	at io.github.tofodroid.mods.mimi.server.midi.transmitter.ServerMusicTransmitterManager.onServerStopping(ServerMusicTransmitterManager.java:95) ~[mimimod-1.20.1-4.0.5.jar%23606!/:1.20.1-4.0.5]
	at io.github.tofodroid.mods.mimi.forge.common.CommonForgeEventHandler.onServerStopping(CommonForgeEventHandler.java:115) ~[mimimod-1.20.1-4.0.5.jar%23606!/:1.20.1-4.0.5]
	at io.github.tofodroid.mods.mimi.forge.common.__CommonForgeEventHandler_onServerStopping_ServerStoppingEvent.invoke(.dynamic) ~[mimimod-1.20.1-4.0.5.jar%23606!/:1.20.1-4.0.5]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStopping(ServerLifecycleHooks.java:122) ~[forge-1.20.1-47.2.21-universal.jar%23712!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:671) ~[server-1.20.1-20230612.114412-srg.jar%23707!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23707!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03Apr2024 19:09:04.935] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 4c6ab9c4-e869-49a2-bf06-d2b8e15a9990`

**Comment by zeven1707** [comment]
Having the same issue. Server won't stop and log spits this out. No one has been on the server while it was running.
MC Version: 1.20.1
MIMI Version 4.0.5

https://pastebin.com/nw4tPg82

**Comment by tofodroid** [comment]
Hi @zeven1707 - It looks like you ran into the same issue that was reported here: https://github.com/tofodroid/mimi-mod/issues/121 which should hopefully be fixed by the new 4.0.6 build that was just released!
