### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by edvgi966** [tofodroid/mimi-mod#132]
**Describe the bug**
Crashes the game when creating a new world, or entering a already created one 

**Crash Logs**
Reported exception thrown!
net.minecraft.ReportedException: mouseClicked event handler
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:444)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at MC-BOOTSTRAP/org.lwjgl@3.3.1+7/org.lwjgl.system.JNI.invokeV(Native Method)
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.1+7/org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at TRANSFORMER/minecraft@1.20.1/com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1173)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.18/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

Caused by: java.lang.NullPointerException: Cannot invoke "com.google.common.collect.BiMap.keySet()" because "this.channelAssignmentMap" is null
	at TRANSFORMER/mimi@1.20.1-3.1.1/io.github.tofodroid.mods.mimi.client.midi.synth.AMIMISynth.allNotesOff(AMIMISynth.java:150)
	at TRANSFORMER/mimi@1.20.1-3.1.1/io.github.tofodroid.mods.mimi.client.midi.synth.MidiMultiSynthManager.close(MidiMultiSynthManager.java:110)
	at TRANSFORMER/mimi@1.20.1-3.1.1/io.github.tofodroid.mods.mimi.client.midi.synth.MidiMultiSynthManager.handleSelfLogOut(MidiMultiSynthManager.java:93)
	at TRANSFORMER/mimi@1.20.1-3.1.1/io.github.tofodroid.mods.mimi.client.midi.synth.__MidiMultiSynthManager_handleSelfLogOut_LoggingOut.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.18/net.minecraftforge.client.ForgeHooksClient.firePlayerLogout(ForgeHooksClient.java:944)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91320_(Minecraft.java:2107)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91399_(Minecraft.java:2089)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_261031_(Minecraft.java:2008)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_245064_(WorldOpenFlows.java:108)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_245184_(CreateWorldScreen.java:226)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_244678_(CreateWorldScreen.java:213)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.handler$eif000$beGone(WorldOpenFlows.java:1525)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_269260_(WorldOpenFlows.java:285)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100972_(CreateWorldScreen.java:212)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_232937_(CreateWorldScreen.java:174)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.components.Button.m_5691_(Button.java:38)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:55)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:175)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:38)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437)
	... 26 more

**Environment (please complete the following information):**
 - OS: 6.9.1-arch1-1, Plasma 6.0.5, kwin
 - Mod Version: 1.20.1-3.1.1
 - Minecraft Version: 1.20.1
 - Forge Version: 47.2.18

**Comment by tofodroid** [comment]
Hello!

It looks like you're using an old version of MIMI. This bug was fixed in the following versions:

1.20.1-3.1.5: https://www.curseforge.com/minecraft/mc-mods/mimi-mod/files/5251783

Or any 4.1.x version.

Please let me know if you continue to have issues on one of those versions!
